package com.joyveb.report.gens.terrace.domain;

public class ParaMerchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.MERCHANTID
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.MERCHANTNAME
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.IPADDR
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.STATUS
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.MERCHANTKEY
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String merchantkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.FTPPATH
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ftppath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.FTPIP
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ftpip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.FTPUSER
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ftpuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.FTPPWD
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ftppwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.FTPPORT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ftpport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.MERCHANTPREFIX
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String merchantprefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.PATTERN
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Short pattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.ENCRYPT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Short encrypt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.RESULTTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Short resulttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PARA_MERCHANT.FTPTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Short ftptype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.MERCHANTID
     *
     * @return the value of T_PARA_MERCHANT.MERCHANTID
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.MERCHANTID
     *
     * @param merchantid the value for T_PARA_MERCHANT.MERCHANTID
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.MERCHANTNAME
     *
     * @return the value of T_PARA_MERCHANT.MERCHANTNAME
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.MERCHANTNAME
     *
     * @param merchantname the value for T_PARA_MERCHANT.MERCHANTNAME
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.IPADDR
     *
     * @return the value of T_PARA_MERCHANT.IPADDR
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.IPADDR
     *
     * @param ipaddr the value for T_PARA_MERCHANT.IPADDR
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.STATUS
     *
     * @return the value of T_PARA_MERCHANT.STATUS
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.STATUS
     *
     * @param status the value for T_PARA_MERCHANT.STATUS
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.MERCHANTKEY
     *
     * @return the value of T_PARA_MERCHANT.MERCHANTKEY
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getMerchantkey() {
        return merchantkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.MERCHANTKEY
     *
     * @param merchantkey the value for T_PARA_MERCHANT.MERCHANTKEY
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMerchantkey(String merchantkey) {
        this.merchantkey = merchantkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.FTPPATH
     *
     * @return the value of T_PARA_MERCHANT.FTPPATH
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getFtppath() {
        return ftppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.FTPPATH
     *
     * @param ftppath the value for T_PARA_MERCHANT.FTPPATH
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setFtppath(String ftppath) {
        this.ftppath = ftppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.FTPIP
     *
     * @return the value of T_PARA_MERCHANT.FTPIP
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getFtpip() {
        return ftpip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.FTPIP
     *
     * @param ftpip the value for T_PARA_MERCHANT.FTPIP
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setFtpip(String ftpip) {
        this.ftpip = ftpip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.FTPUSER
     *
     * @return the value of T_PARA_MERCHANT.FTPUSER
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getFtpuser() {
        return ftpuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.FTPUSER
     *
     * @param ftpuser the value for T_PARA_MERCHANT.FTPUSER
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setFtpuser(String ftpuser) {
        this.ftpuser = ftpuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.FTPPWD
     *
     * @return the value of T_PARA_MERCHANT.FTPPWD
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getFtppwd() {
        return ftppwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.FTPPWD
     *
     * @param ftppwd the value for T_PARA_MERCHANT.FTPPWD
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setFtppwd(String ftppwd) {
        this.ftppwd = ftppwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.FTPPORT
     *
     * @return the value of T_PARA_MERCHANT.FTPPORT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getFtpport() {
        return ftpport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.FTPPORT
     *
     * @param ftpport the value for T_PARA_MERCHANT.FTPPORT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setFtpport(String ftpport) {
        this.ftpport = ftpport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.MERCHANTPREFIX
     *
     * @return the value of T_PARA_MERCHANT.MERCHANTPREFIX
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getMerchantprefix() {
        return merchantprefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.MERCHANTPREFIX
     *
     * @param merchantprefix the value for T_PARA_MERCHANT.MERCHANTPREFIX
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMerchantprefix(String merchantprefix) {
        this.merchantprefix = merchantprefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.PATTERN
     *
     * @return the value of T_PARA_MERCHANT.PATTERN
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Short getPattern() {
        return pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.PATTERN
     *
     * @param pattern the value for T_PARA_MERCHANT.PATTERN
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setPattern(Short pattern) {
        this.pattern = pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.ENCRYPT
     *
     * @return the value of T_PARA_MERCHANT.ENCRYPT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Short getEncrypt() {
        return encrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.ENCRYPT
     *
     * @param encrypt the value for T_PARA_MERCHANT.ENCRYPT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setEncrypt(Short encrypt) {
        this.encrypt = encrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.RESULTTYPE
     *
     * @return the value of T_PARA_MERCHANT.RESULTTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Short getResulttype() {
        return resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.RESULTTYPE
     *
     * @param resulttype the value for T_PARA_MERCHANT.RESULTTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setResulttype(Short resulttype) {
        this.resulttype = resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PARA_MERCHANT.FTPTYPE
     *
     * @return the value of T_PARA_MERCHANT.FTPTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Short getFtptype() {
        return ftptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PARA_MERCHANT.FTPTYPE
     *
     * @param ftptype the value for T_PARA_MERCHANT.FTPTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setFtptype(Short ftptype) {
        this.ftptype = ftptype;
    }
}