package com.joyveb.report.gens.terrace.domain;

public class StatWagerdata extends StatWagerdataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.MERTRADECOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Long mertradecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.MERTRADEMONEY
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Long mertrademoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.TRADECOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Long tradecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.TRADEAMOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Long tradeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.EXTRAFIELD1
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private Long extrafield1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.EXTRAFIELD2
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String extrafield2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.MERTRADECOUNT
     *
     * @return the value of T_STAT_WAGERDATA.MERTRADECOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Long getMertradecount() {
        return mertradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.MERTRADECOUNT
     *
     * @param mertradecount the value for T_STAT_WAGERDATA.MERTRADECOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMertradecount(Long mertradecount) {
        this.mertradecount = mertradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.MERTRADEMONEY
     *
     * @return the value of T_STAT_WAGERDATA.MERTRADEMONEY
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Long getMertrademoney() {
        return mertrademoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.MERTRADEMONEY
     *
     * @param mertrademoney the value for T_STAT_WAGERDATA.MERTRADEMONEY
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMertrademoney(Long mertrademoney) {
        this.mertrademoney = mertrademoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.TRADECOUNT
     *
     * @return the value of T_STAT_WAGERDATA.TRADECOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Long getTradecount() {
        return tradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.TRADECOUNT
     *
     * @param tradecount the value for T_STAT_WAGERDATA.TRADECOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setTradecount(Long tradecount) {
        this.tradecount = tradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.TRADEAMOUNT
     *
     * @return the value of T_STAT_WAGERDATA.TRADEAMOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Long getTradeamount() {
        return tradeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.TRADEAMOUNT
     *
     * @param tradeamount the value for T_STAT_WAGERDATA.TRADEAMOUNT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setTradeamount(Long tradeamount) {
        this.tradeamount = tradeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.EXTRAFIELD1
     *
     * @return the value of T_STAT_WAGERDATA.EXTRAFIELD1
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Long getExtrafield1() {
        return extrafield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.EXTRAFIELD1
     *
     * @param extrafield1 the value for T_STAT_WAGERDATA.EXTRAFIELD1
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setExtrafield1(Long extrafield1) {
        this.extrafield1 = extrafield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.EXTRAFIELD2
     *
     * @return the value of T_STAT_WAGERDATA.EXTRAFIELD2
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getExtrafield2() {
        return extrafield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.EXTRAFIELD2
     *
     * @param extrafield2 the value for T_STAT_WAGERDATA.EXTRAFIELD2
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setExtrafield2(String extrafield2) {
        this.extrafield2 = extrafield2;
    }
}