package com.joyveb.report.gens.terrace.domain;

import com.joyveb.util.CustomDateSerializer;
import java.math.BigDecimal;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

public class StatWagerdataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.LTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String ltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.MERCHANTID
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.PERIOD
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private BigDecimal period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.REGION
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAT_WAGERDATA.STATDATE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
     @JsonSerialize (using = CustomDateSerializer. class )
    private Date statdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.LTYPE
     *
     * @return the value of T_STAT_WAGERDATA.LTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getLtype() {
        return ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.LTYPE
     *
     * @param ltype the value for T_STAT_WAGERDATA.LTYPE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setLtype(String ltype) {
        this.ltype = ltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.MERCHANTID
     *
     * @return the value of T_STAT_WAGERDATA.MERCHANTID
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.MERCHANTID
     *
     * @param merchantid the value for T_STAT_WAGERDATA.MERCHANTID
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.PERIOD
     *
     * @return the value of T_STAT_WAGERDATA.PERIOD
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public BigDecimal getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.PERIOD
     *
     * @param period the value for T_STAT_WAGERDATA.PERIOD
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setPeriod(BigDecimal period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.REGION
     *
     * @return the value of T_STAT_WAGERDATA.REGION
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.REGION
     *
     * @param region the value for T_STAT_WAGERDATA.REGION
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAT_WAGERDATA.STATDATE
     *
     * @return the value of T_STAT_WAGERDATA.STATDATE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public Date getStatdate() {
        return statdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAT_WAGERDATA.STATDATE
     *
     * @param statdate the value for T_STAT_WAGERDATA.STATDATE
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void setStatdate(Date statdate) {
        this.statdate = statdate;
    }
}