package com.joyveb.report.gens.terrace.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ibatis.sqlmap.client.SqlMapExecutor;
import com.joyveb.report.gens.terrace.dao.iface.ParaMerchantDAO;
import com.joyveb.report.gens.terrace.domain.ParaMerchant;
import com.joyveb.report.gens.terrace.domain.ParaMerchantExample;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import javax.annotation.PostConstruct;
import org.springframework.orm.ibatis.SqlMapClientCallback;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Component;

@Component(ParaMerchantDAOImpl.BEAN_NAME)
public class ParaMerchantDAOImpl extends SqlMapClientDaoSupport implements ParaMerchantDAO {
    public static final String BEAN_NAME="paraMerchantDAO";

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    @javax.annotation.Resource(name = "sqlMapClient")
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public ParaMerchantDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int countByExample(ParaMerchantExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("T_PARA_MERCHANT.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int deleteByExample(ParaMerchantExample example) {
        int rows = getSqlMapClientTemplate().delete("T_PARA_MERCHANT.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int deleteByPrimaryKey(String merchantid) {
        ParaMerchant _key = new ParaMerchant();
        _key.setMerchantid(merchantid);
        int rows = getSqlMapClientTemplate().delete("T_PARA_MERCHANT.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void insert(ParaMerchant record) {
        getSqlMapClientTemplate().insert("T_PARA_MERCHANT.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void insertSelective(ParaMerchant record) {
        getSqlMapClientTemplate().insert("T_PARA_MERCHANT.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<ParaMerchant> selectByExample(ParaMerchantExample example) {
        List<ParaMerchant> list = getSqlMapClientTemplate().queryForList("T_PARA_MERCHANT.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public ParaMerchant selectByPrimaryKey(String merchantid) {
        ParaMerchant _key = new ParaMerchant();
        _key.setMerchantid(merchantid);
        ParaMerchant record = (ParaMerchant) getSqlMapClientTemplate().queryForObject("T_PARA_MERCHANT.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByExampleSelective(ParaMerchant record, ParaMerchantExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_PARA_MERCHANT.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByExample(ParaMerchant record, ParaMerchantExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_PARA_MERCHANT.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByPrimaryKeySelective(ParaMerchant record) {
        int rows = getSqlMapClientTemplate().update("T_PARA_MERCHANT.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByPrimaryKey(ParaMerchant record) {
        int rows = getSqlMapClientTemplate().update("T_PARA_MERCHANT.updateByPrimaryKey", record);
        return rows;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<ParaMerchant> findByPage(ParaMerchantExample example, int startRow, int endRow) {
        return this.findByPage(example, startRow, endRow, null);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<ParaMerchant> findByPage(ParaMerchantExample example, int startRow, int endRow, String orderByClause) {
        	example.setStartRow(String.valueOf(startRow));
        	example.setEndRow(String.valueOf(endRow));
        	example.setOrderByClause(orderByClause);
        	return getSqlMapClientTemplate().queryForList("T_PARA_MERCHANT.findByPage",example);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public void batchInsertSelective(final List<ParaMerchant> list) {
        getSqlMapClientTemplate().execute(new SqlMapClientCallback(){
            	public Object doInSqlMapClient(SqlMapExecutor executor)
            		throws SQLException {
                		executor.startBatch();
                		for(ParaMerchant item : list){
                    			executor.insert("T_PARA_MERCHANT.insertSelective",item);
                    		}
                    		executor.executeBatch();
                    		return null;
                    	}
                });
            }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public int sumByExample(ParaMerchantExample example) {
        	Integer sum = (Integer)  getSqlMapClientTemplate().queryForObject("T_PARA_MERCHANT.sumByExample", example);
        	return sum;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<HashMap> groupByExample(ParaMerchantExample example) {
        	return getSqlMapClientTemplate().queryForList("T_PARA_MERCHANT.groupByExample",example);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public void batchUpdateSelective(final List<ParaMerchant> list) {
        getSqlMapClientTemplate().execute(new SqlMapClientCallback(){
            	public Object doInSqlMapClient(SqlMapExecutor executor)
            		throws SQLException {
                		executor.startBatch();
                		 for(ParaMerchant item : list){
                    			executor.update("T_PARA_MERCHANT.updateByPrimaryKeySelective",item);
                    		}
                    		executor.executeBatch();
                    		return null;
                    	}
                });
            }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public void batchDeleteSelective(final List<ParaMerchant> list) {
        getSqlMapClientTemplate().execute(new SqlMapClientCallback(){
            	public Object doInSqlMapClient(SqlMapExecutor executor)
            		throws SQLException {
                		executor.startBatch();
                		 for(ParaMerchant item : list){
                    			executor.delete("T_PARA_MERCHANT.deleteByPrimaryKey",item);
                    		}
                    		executor.executeBatch();
                    		return null;
                    	}
                });
            }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    @PostConstruct
    public void initSqlMapClient() {
            super.setSqlMapClient(sqlMapClient);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_PARA_MERCHANT
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<ParaMerchant> selectByExampleAnd(ParaMerchantExample example) {
        List<ParaMerchant> list = getSqlMapClientTemplate().queryForList("T_PARA_MERCHANT.selectByExampleAnd", example);
        return list;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PARA_MERCHANT
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    protected static class UpdateByExampleParms extends ParaMerchantExample {
        private Object record;

        public UpdateByExampleParms(Object record, ParaMerchantExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}