package com.joyveb.report.gens.terrace.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ibatis.sqlmap.client.SqlMapExecutor;
import com.joyveb.report.gens.terrace.dao.iface.StatWagerdataDAO;
import com.joyveb.report.gens.terrace.domain.StatWagerdata;
import com.joyveb.report.gens.terrace.domain.StatWagerdataExample;
import com.joyveb.report.gens.terrace.domain.StatWagerdataKey;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import javax.annotation.PostConstruct;
import org.springframework.orm.ibatis.SqlMapClientCallback;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Component;

@Component(StatWagerdataDAOImpl.BEAN_NAME)
public class StatWagerdataDAOImpl extends SqlMapClientDaoSupport implements StatWagerdataDAO {
    public static final String BEAN_NAME="statWagerdataDAO";

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    @javax.annotation.Resource(name = "sqlMapClient")
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public StatWagerdataDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int countByExample(StatWagerdataExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("T_STAT_WAGERDATA.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int deleteByExample(StatWagerdataExample example) {
        int rows = getSqlMapClientTemplate().delete("T_STAT_WAGERDATA.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int deleteByPrimaryKey(StatWagerdataKey _key) {
        int rows = getSqlMapClientTemplate().delete("T_STAT_WAGERDATA.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void insert(StatWagerdata record) {
        getSqlMapClientTemplate().insert("T_STAT_WAGERDATA.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public void insertSelective(StatWagerdata record) {
        getSqlMapClientTemplate().insert("T_STAT_WAGERDATA.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<StatWagerdata> selectByExample(StatWagerdataExample example) {
        List<StatWagerdata> list = getSqlMapClientTemplate().queryForList("T_STAT_WAGERDATA.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public StatWagerdata selectByPrimaryKey(StatWagerdataKey _key) {
        StatWagerdata record = (StatWagerdata) getSqlMapClientTemplate().queryForObject("T_STAT_WAGERDATA.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByExampleSelective(StatWagerdata record, StatWagerdataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_STAT_WAGERDATA.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByExample(StatWagerdata record, StatWagerdataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_STAT_WAGERDATA.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByPrimaryKeySelective(StatWagerdata record) {
        int rows = getSqlMapClientTemplate().update("T_STAT_WAGERDATA.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    public int updateByPrimaryKey(StatWagerdata record) {
        int rows = getSqlMapClientTemplate().update("T_STAT_WAGERDATA.updateByPrimaryKey", record);
        return rows;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<StatWagerdata> findByPage(StatWagerdataExample example, int startRow, int endRow) {
        return this.findByPage(example, startRow, endRow, null);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<StatWagerdata> findByPage(StatWagerdataExample example, int startRow, int endRow, String orderByClause) {
        	example.setStartRow(String.valueOf(startRow));
        	example.setEndRow(String.valueOf(endRow));
        	example.setOrderByClause(orderByClause);
        	return getSqlMapClientTemplate().queryForList("T_STAT_WAGERDATA.findByPage",example);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public void batchInsertSelective(final List<StatWagerdata> list) {
        getSqlMapClientTemplate().execute(new SqlMapClientCallback(){
            	public Object doInSqlMapClient(SqlMapExecutor executor)
            		throws SQLException {
                		executor.startBatch();
                		for(StatWagerdata item : list){
                    			executor.insert("T_STAT_WAGERDATA.insertSelective",item);
                    		}
                    		executor.executeBatch();
                    		return null;
                    	}
                });
            }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public int sumByExample(StatWagerdataExample example) {
        	Integer sum = (Integer)  getSqlMapClientTemplate().queryForObject("T_STAT_WAGERDATA.sumByExample", example);
        	return sum;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<HashMap> groupByExample(StatWagerdataExample example) {
        	return getSqlMapClientTemplate().queryForList("T_STAT_WAGERDATA.groupByExample",example);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public void batchUpdateSelective(final List<StatWagerdata> list) {
        getSqlMapClientTemplate().execute(new SqlMapClientCallback(){
            	public Object doInSqlMapClient(SqlMapExecutor executor)
            		throws SQLException {
                		executor.startBatch();
                		 for(StatWagerdata item : list){
                    			executor.update("T_STAT_WAGERDATA.updateByPrimaryKeySelective",item);
                    		}
                    		executor.executeBatch();
                    		return null;
                    	}
                });
            }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public void batchDeleteSelective(final List<StatWagerdata> list) {
        getSqlMapClientTemplate().execute(new SqlMapClientCallback(){
            	public Object doInSqlMapClient(SqlMapExecutor executor)
            		throws SQLException {
                		executor.startBatch();
                		 for(StatWagerdata item : list){
                    			executor.delete("T_STAT_WAGERDATA.deleteByPrimaryKey",item);
                    		}
                    		executor.executeBatch();
                    		return null;
                    	}
                });
            }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    @PostConstruct
    public void initSqlMapClient() {
            super.setSqlMapClient(sqlMapClient);
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table T_STAT_WAGERDATA
    *
    * @generated Sat Mar 11 06:42:48 CST 2014
    */
    public List<StatWagerdata> selectByExampleAnd(StatWagerdataExample example) {
        List<StatWagerdata> list = getSqlMapClientTemplate().queryForList("T_STAT_WAGERDATA.selectByExampleAnd", example);
        return list;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_STAT_WAGERDATA
     *
     * @mbggenerated Sat Mar 15 06:42:48 CST 2014
     */
    protected static class UpdateByExampleParms extends StatWagerdataExample {
        private Object record;

        public UpdateByExampleParms(Object record, StatWagerdataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}